export default Images = {
    Pamper_logo: require("../Assets/PamperLogo.png"),
    facebook_icon: require("../Assets/facebook_social_icon.png"),
    apple_icon: require("../Assets/apple_social_icon.png"),
    google_icon: require("../Assets/google_social_icon.png"),
    calendar: require('../Assets/calendar.png'),
    family_img: require('../Assets/family_img.png'),
    visual: require('../Assets/visual.png'),
    bell: require('../Assets/bell.png'),
    giftBoxes: require('../Assets/giftboxes.png'),
    Onboarding: require('../Assets/Onboarding.png'),
    Onboarding2: require('../Assets/Onboarding2.png'),
    senza: require('../Assets/Senza.png'),
    baby: require('../Assets/baby.jpeg'),
    baby2: require('../Assets/baby2.jpg'),
}